import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, signInWithRedirect, getRedirectResult, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import { getFirestore, doc, onSnapshot, setDoc } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";

// Dán cấu hình Web App của Firebase Console vào firebaseConfig bên dưới.
const firebaseConfig = {
  apiKey: "AIzaSyDdEaJvVRRzfcM_IkTjdP0Livz52IQqrMs",
  authDomain: "life-money-f6a11.firebaseapp.com",
  projectId: "life-money-f6a11",
  storageBucket: "life-money-f6a11.firebasestorage.app",
  messagingSenderId: "284442463922",
  appId: "1:284442463922:web:4a0ac661bcdf6f652d83ab",
  measurementId: "G-1WQ6WPG39C"
};
const configured = !Object.values(firebaseConfig).some(v=>String(v).includes("PASTE_"));
const $=id=>document.getElementById(id), pad=n=>String(n).padStart(2,'0');
const iso=d=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());
const parseDate=s=>{const a=String(s).split('-').map(Number);return new Date(a[0],a[1]-1,a[2],12)};
const monthKey=d=>d.getFullYear()+'-'+pad(d.getMonth()+1);
const money=n=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:0}).format(Number(n)||0)+' ₫';
const monthName=d=>new Intl.DateTimeFormat('vi-VN',{month:'long',year:'numeric'}).format(d);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=new Date();today.setHours(12,0,0,0);
let cursor=new Date(today.getFullYear(),today.getMonth(),1,12),selected=iso(today),user=null,unsubscribe=null,saveTimer=null,modalSubmit=null,editId=null,saveVersion=0,remoteVersion=0,appData={transactions:[],tasks:[],settings:{goal:10000000,budget:8000000}},ready=false;
let auth,db;
function notify(s){$('toast').textContent=s;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2600)}
function lunarDay(dd,mm,yy){
 const PI=Math.PI;
 function jd(d,m,y){let a=Math.floor((14-m)/12),y2=y+4800-a,m2=m+12*a-3,j=d+Math.floor((153*m2+2)/5)+365*y2+Math.floor(y2/4)-Math.floor(y2/100)+Math.floor(y2/400)-32045;if(j<2299161)j=d+Math.floor((153*m2+2)/5)+365*y2+Math.floor(y2/4)-32083;return j}
 function nm(k){let T=k/1236.85,T2=T*T,T3=T2*T,dr=PI/180,J=2415020.75933+29.53058868*k+0.0001178*T2-0.000000155*T3+0.00033*Math.sin((166.56+132.87*T-0.009173*T2)*dr),M=359.2242+29.10535608*k-0.0000333*T2-0.00000347*T3,Mp=306.0253+385.81691806*k+0.0107306*T2+0.00001236*T3,F=21.2964+390.67050646*k-0.0016528*T2-0.00000239*T3,C=(0.1734-0.000393*T)*Math.sin(M*dr)+0.0021*Math.sin(2*dr*M)-0.4068*Math.sin(Mp*dr)+0.0161*Math.sin(2*dr*Mp)-0.0004*Math.sin(3*dr*Mp)+0.0104*Math.sin(2*dr*F)-0.0051*Math.sin((M+Mp)*dr)-0.0074*Math.sin((M-Mp)*dr)+0.0004*Math.sin((2*F+M)*dr)-0.0004*Math.sin((2*F-M)*dr)-0.0006*Math.sin((2*F+Mp)*dr)+0.001*Math.sin((2*F-Mp)*dr)+0.0005*Math.sin((2*Mp+M)*dr),dt=T< -11?0.001+0.000839*T+0.0002261*T2-0.00000845*T3-0.000000081*T*T3:-0.000278+0.000265*T+0.000262*T2;return Math.floor(J+C-dt+0.5+7/24)}
 function sun(day){let T=(day-2451545.5)/36525,T2=T*T,dr=PI/180,M=357.5291+35999.0503*T-0.0001559*T2-0.00000048*T*T2,L0=280.46645+36000.76983*T+0.0003032*T2,DL=(1.9146-0.004817*T-0.000014*T2)*Math.sin(dr*M)+(0.019993-0.000101*T)*Math.sin(2*dr*M)+0.00029*Math.sin(3*dr*M),L=(L0+DL)*dr;L-=2*PI*Math.floor(L/(2*PI));return Math.floor(L/PI*6)}
 function m11(y){let off=jd(31,12,y)-2415021,k=Math.floor(off/29.530588853),n=nm(k);if(sun(n)>=9)n=nm(k-1);return n}
 function leapOff(a){let k=Math.floor((a-2415021.076998695)/29.530588853),last=0,i=1,arc=sun(nm(k+i));do{last=arc;i++;arc=sun(nm(k+i))}while(arc!==last&&i<15);return i-1}
 let day=jd(dd,mm,yy),k=Math.floor((day-2415021.076998695)/29.530588853),n=nm(k);if(n>day)n=nm(k-1);let a=m11(yy),b=a,year;if(a>=n){year=yy;a=m11(yy-1)}else{year=yy+1;b=m11(yy+1)}let ld=day-n+1,diff=Math.floor((n-a)/29),lm=diff+11,leap=0;if(b-a>365){let off=leapOff(a);if(diff>=off){lm=diff+10;if(diff===off-1)leap=1}}if(lm>12)lm-=12;if(lm>=11&&diff<4)year--;return {day:ld,month:lm,year,leap}
}
function lunar(s){try{let d=parseDate(s),l=lunarDay(d.getDate(),d.getMonth()+1,d.getFullYear());return l.day+'/'+l.month+(l.leap?' nhuận':'')}catch{return ''}}
function dateLabel(s){return new Intl.DateTimeFormat('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(parseDate(s))}
function transactionsMonth(m){return appData.transactions.filter(t=>String(t.date||'').startsWith(m))}
function totals(m){return transactionsMonth(m).reduce((a,t)=>{a[t.type==='income'?'income':'expense']+=Number(t.amount)||0;return a},{income:0,expense:0})}
function tasksOn(s){return appData.tasks.filter(t=>t.date===s)}
function newId(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random().toString(16).slice(2)}
function saveCloud(){
 if(!user||!ready)return;
 clearTimeout(saveTimer);const version=++saveVersion;saveTimer=setTimeout(async()=>{
  try{await setDoc(doc(db,'users',user.uid,'app','data'),{...appData,updatedAt:Date.now(),schemaVersion:1});remoteVersion=version;$('subtitle').textContent='Đã đồng bộ · '+user.email}
  catch(e){console.error(e);notify('Không thể đồng bộ. Kiểm tra kết nối và quyền Firestore.')}
 },350);
}
function renderCalendar(id){let el=$(id),y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1,12),start=(first.getDay()+6)%7,html=['T2','T3','T4','T5','T6','T7','CN'].map(w=>`<div class="weekday">${w}</div>`).join('');for(let i=0;i<42;i++){let d=new Date(y,m,1-start+i,12),s=iso(d),inside=d.getMonth()===m,ts=tasksOn(s),tx=appData.transactions.filter(t=>t.date===s);html+=`<button class="day ${s===selected?'sel':''} ${inside?'':'out'} ${s===iso(today)?'today':''}" data-day="${s}" aria-label="${esc(dateLabel(s))}"><div class="solar">${d.getDate()}</div><div class="lunar">${lunar(s)}</div>${ts.slice(0,2).map(t=>`<div class="eventline" style="color:${t.kind==='event'?'#d74763':t.kind==='health'?'#169b6b':'#3388e9'}">● ${esc(t.title)}</div>`).join('')}${tx.length?`<div class="eventline" style="color:#df8536">● ${tx.length} giao dịch</div>`:''}${ts.length>2?`<div class="eventline muted">+${ts.length-2} mục</div>`:''}</button>`}el.innerHTML=html;el.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{selected=b.dataset.day;let d=parseDate(selected);if(d.getMonth()!==cursor.getMonth())cursor=new Date(d.getFullYear(),d.getMonth(),1,12);renderAll();renderDayDetail()})}
function renderAgenda(){let arr=tasksOn(selected).sort((a,b)=>(a.time||'').localeCompare(b.time||''));$('agenda').innerHTML=`<div class="muted small" style="margin-top:8px">${esc(dateLabel(selected))} · Âm lịch ${lunar(selected)}</div>`+(arr.length?arr.map(t=>`<div class="item"><input type="checkbox" data-check="${esc(t.id)}" ${t.done?'checked':''}><div class="itembody"><div class="itemtitle">${esc(t.title)}</div><div class="muted small">${esc(t.time||'Chưa đặt giờ')} · ${t.kind==='event'?'Sự kiện':t.kind==='health'?'Sức khỏe':'Công việc'}</div></div></div>`).join(''):'<div class="empty">Chưa có kế hoạch trong ngày.</div>');wireChecks($('agenda'))}
function renderRecent(){let arr=[...appData.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);$('recent').innerHTML=arr.length?arr.map(t=>`<div class="item"><div class="itembody"><div class="itemtitle">${esc(t.title)}</div><div class="muted small">${esc(t.date)} · ${esc(t.category)}</div></div><b class="${t.type==='income'?'green':'red'}" style="white-space:nowrap">${t.type==='income'?'+':'−'}${money(t.amount)}</b></div>`).join(''):'<div class="empty">Chưa có giao dịch.</div>'}
function renderChart(){let ms=[];for(let i=3;i>=0;i--){let d=new Date(cursor.getFullYear(),cursor.getMonth()-i,1,12),t=totals(monthKey(d));ms.push({label:'T'+(d.getMonth()+1),...t})}let max=Math.max(1,...ms.flatMap(x=>[x.income,x.expense]));$('chart').innerHTML=`<div class="muted small" style="margin:12px 0">🟢 Thu　🟠 Chi</div><div style="display:flex;gap:12px;height:130px;align-items:flex-end;border-bottom:1px solid #e5ebf1">${ms.map(x=>`<div style="flex:1;text-align:center"><div style="height:102px;display:flex;align-items:flex-end;justify-content:center;gap:3px"><div title="${money(x.income)}" style="width:34%;height:${x.income/max*100}%;background:#25ad86;border-radius:3px 3px 0 0"></div><div title="${money(x.expense)}" style="width:34%;height:${x.expense/max*100}%;background:#f6a05c;border-radius:3px 3px 0 0"></div></div><div class="muted small" style="margin-top:7px">${x.label}</div></div>`).join('')}</div>`}
function renderDayDetail(){let ts=tasksOn(selected),tx=appData.transactions.filter(t=>t.date===selected);$('daydetail').innerHTML=`<b>${esc(dateLabel(selected))}</b><div class="muted small" style="margin:5px 0 12px">Âm lịch ${lunar(selected)}</div>${ts.map(t=>`<div class="item"><input type="checkbox" data-check="${esc(t.id)}" ${t.done?'checked':''}><div class="itembody"><div class="itemtitle">${esc(t.title)}</div><div class="muted small">${esc(t.time||'')} · ${t.kind==='event'?'Sự kiện':t.kind==='health'?'Sức khỏe':'Công việc'}</div></div><button class="btn" data-edittask="${esc(t.id)}">Sửa</button></div>`).join('')}${tx.map(t=>`<div class="item"><div class="itembody">${esc(t.title)}<div class="muted small">${esc(t.category)}</div></div><b class="${t.type==='income'?'green':'red'}">${t.type==='income'?'+':'−'}${money(t.amount)}</b></div>`).join('')}${!ts.length&&!tx.length?'<div class="empty">Chưa có dữ liệu trong ngày.</div>':''}<div class="row" style="margin-top:12px"><button class="btn primary" id="daytask">＋ Công việc / sự kiện</button><button class="btn" id="daytx">＋ Thu chi</button></div>`;$('daytask').onclick=()=>openTask();$('daytx').onclick=()=>openFinance();$('daydetail').querySelectorAll('[data-edittask]').forEach(b=>b.onclick=()=>openTask(b.dataset.edittask));wireChecks($('daydetail'))}
function renderFinance(){let type=$('filtertype').value,m=$('filtermonth').value||monthKey(cursor),arr=[...appData.transactions].filter(t=>(type==='all'||t.type===type)&&String(t.date).startsWith(m)).sort((a,b)=>b.date.localeCompare(a.date));$('financelist').innerHTML=arr.length?arr.map(t=>`<div class="item"><div style="font-size:20px">${t.type==='income'?'💰':'🧾'}</div><div class="itembody"><div class="itemtitle">${esc(t.title)}</div><div class="muted small">${esc(t.category)} · ${esc(t.date)}${t.note?' · '+esc(t.note):''}</div></div><b class="${t.type==='income'?'green':'red'}" style="white-space:nowrap">${t.type==='income'?'+':'−'}${money(t.amount)}</b><button class="btn" data-edittx="${esc(t.id)}">✎</button><button class="btn" data-deltx="${esc(t.id)}">×</button></div>`).join(''):'<div class="empty">Không có giao dịch trong tháng này.</div>';document.querySelectorAll('[data-edittx]').forEach(b=>b.onclick=()=>openFinance(b.dataset.edittx));document.querySelectorAll('[data-deltx]').forEach(b=>b.onclick=()=>deleteTx(b.dataset.deltx))}
function renderTasks(){let kind=$('taskfilter').value,status=$('taskstatus').value,arr=[...appData.tasks].filter(t=>(kind==='all'||t.kind===kind)&&(status==='all'||(status==='done'?t.done:!t.done))).sort((a,b)=>a.date.localeCompare(b.date)||(a.time||'').localeCompare(b.time||''));$('tasklist').innerHTML=arr.length?arr.map(t=>`<div class="item"><input type="checkbox" data-check="${esc(t.id)}" ${t.done?'checked':''}><div class="itembody"><div class="itemtitle" style="${t.done?'text-decoration:line-through;color:#8994a2':''}">${esc(t.title)}</div><div class="muted small">${esc(t.date)} ${esc(t.time||'')} · ${esc(t.note||'')}</div><span class="pill">${t.kind==='event'?'Sự kiện':t.kind==='health'?'Sức khỏe':'Công việc'}</span></div><button class="btn" data-edittask="${esc(t.id)}">✎</button><button class="btn" data-deltask="${esc(t.id)}">×</button></div>`).join(''):'<div class="empty">Chưa có mục phù hợp.</div>';wireChecks($('tasklist'));$('tasklist').querySelectorAll('[data-edittask]').forEach(b=>b.onclick=()=>openTask(b.dataset.edittask));$('tasklist').querySelectorAll('[data-deltask]').forEach(b=>b.onclick=()=>{if(confirm('Xóa công việc/sự kiện này?')){appData.tasks=appData.tasks.filter(t=>t.id!==b.dataset.deltask);saveCloud();renderAll()}})}
function renderStats(){let m=$('statsmonth').value||monthKey(today),t=totals(m),goal=Number(appData.settings.goal)||0,budget=Number(appData.settings.budget)||0;$('statssummary').innerHTML=`<div class="cards"><div class="card"><div class="muted">Tổng thu</div><div class="metric green">${money(t.income)}</div></div><div class="card"><div class="muted">Tổng chi</div><div class="metric red">${money(t.expense)}</div></div><div class="card"><div class="muted">Chênh lệch</div><div class="metric">${money(t.income-t.expense)}</div></div></div><div class="muted small">Ngân sách: ${money(budget)} · ${budget?Math.round(t.expense/budget*100)+'% đã dùng':'Chưa đặt ngân sách'}</div><div class="bar" style="margin:8px 0"><span style="width:${budget?Math.min(100,t.expense/budget*100):0}%;background:${budget&&t.expense>budget?'#d34b4b':'#119b78'}"></span></div><div class="muted small">Mục tiêu tiết kiệm: ${money(goal)}</div>`;let cats={};transactionsMonth(m).filter(x=>x.type==='expense').forEach(x=>cats[x.category]=(cats[x.category]||0)+(Number(x.amount)||0));let es=Object.entries(cats).sort((a,b)=>b[1]-a[1]),sum=es.reduce((n,x)=>n+x[1],0);$('categorychart').innerHTML=es.length?es.map(([n,v])=>`<div style="margin:14px 0"><div class="row"><span>${esc(n)}</span><b>${money(v)}</b></div><div class="bar" style="margin-top:6px"><span style="width:${sum?v/sum*100:0}%"></span></div></div>`).join(''):'<div class="empty">Thêm khoản chi để xem phân tích.</div>'}
function renderAll(){let t=totals(monthKey(today));$('income').textContent=money(t.income);$('expense').textContent=money(t.expense);$('balance').textContent=money(t.income-t.expense);$('monthtitle').textContent='Lịch tháng '+monthName(cursor);$('monthtitle2').textContent='Lịch tháng '+monthName(cursor);renderCalendar('calendar');renderCalendar('calendar2');renderAgenda();renderRecent();renderChart();renderFinance();renderTasks();renderStats();let saved=Math.max(0,t.income-t.expense),goal=Number(appData.settings.goal)||0;$('saving').textContent=money(saved);$('savingbar').style.width=(goal?Math.min(100,saved/goal*100):0)+'%';$('savinglabel').textContent=goal?'Mục tiêu '+money(goal)+' · '+Math.round(saved/goal*100)+'% hoàn thành':'Chưa đặt mục tiêu';$('goal').value=goal;$('budget').value=appData.settings.budget||0}
function goto(p){document.querySelectorAll('[id^="page-"]').forEach(x=>x.classList.add('hidden'));$('page-'+p).classList.remove('hidden');document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if(p==='calendar')renderDayDetail()}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>goto(b.dataset.page));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>goto(b.dataset.goto));
function move(n){cursor=new Date(cursor.getFullYear(),cursor.getMonth()+n,1,12);renderAll()}
$('prev').onclick=$('prev2').onclick=()=>move(-1);$('next').onclick=$('next2').onclick=()=>move(1);$('today').onclick=$('today2').onclick=()=>{cursor=new Date(today.getFullYear(),today.getMonth(),1,12);selected=iso(today);renderAll();renderDayDetail()};
function inputField(label,name,type,value,opts='',wide=false){return `<div class="${wide?'wide':''}"><label>${label}</label>${type==='select'?`<select class="field" name="${name}" ${opts}>${value}</select>`:`<input class="field" name="${name}" type="${type}" value="${esc(value??'')}" ${opts}>`}</div>`}
function showModal(title,fields,fn,existing){$('modaltitle').textContent=title;$('formfields').innerHTML=fields;$('modal').classList.add('open');modalSubmit=fn;if(existing)for(let [k,v] of Object.entries(existing)){let f=$('formfields').querySelector(`[name="${k}"]`);if(f)f.value=v}setTimeout(()=> $('formfields').querySelector('input,select')?.focus(),50)}
function closeModal(){$('modal').classList.remove('open');modalSubmit=null}
$('close').onclick=$('cancel').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};$('form').onsubmit=e=>{e.preventDefault();if(!modalSubmit)return;const result=modalSubmit(new FormData($('form')));if(result!==false){closeModal();saveCloud();renderAll();renderDayDetail();notify(result||'Đã lưu.')}};const categories=['Ăn uống','Sinh hoạt','Đi lại','Mua sắm','Hóa đơn','Sức khỏe','Giải trí','Giáo dục','Lương','Thưởng','Đầu tư','Khác'];
function openFinance(id){let old=id?appData.transactions.find(x=>x.id===id):null;let options=(arr,sel)=>arr.map(([v,l])=>`<option value="${v}" ${v===sel?'selected':''}>${l}</option>`).join('');let f=inputField('Loại giao dịch','type','select',options([['expense','Khoản chi'],['income','Khoản thu']],old?.type||'expense'),'required')+inputField('Số tiền (₫)','amount','number',old?.amount||'','min="1" step="1000" required')+inputField('Tên giao dịch','title','text',old?.title||'','maxlength="100" required',true)+inputField('Danh mục','category','select',options(categories.map(x=>[x,x]),old?.category||'Ăn uống'),'required')+inputField('Ngày','date','date',old?.date||selected,'required')+inputField('Ghi chú','note','text',old?.note||'','maxlength="250"',true);showModal(old?'Sửa giao dịch':'Thêm giao dịch',f,fd=>{let amount=Number(fd.get('amount')),title=String(fd.get('title')||'').trim(),date=fd.get('date');if(!title||!date||!Number.isFinite(amount)||amount<=0){notify('Vui lòng nhập tên, ngày và số tiền hợp lệ.');return false}let obj={id:id||newId(),type:fd.get('type'),amount,title,category:fd.get('category'),date,note:String(fd.get('note')||'').trim(),created:Date.now()};appData.transactions=id?appData.transactions.map(x=>x.id===id?obj:x):[...appData.transactions,obj];return 'Đã lưu giao dịch.'},old)}
function openTask(id){let old=id?appData.tasks.find(x=>x.id===id):null;let options=(arr,sel)=>arr.map(([v,l])=>`<option value="${v}" ${v===sel?'selected':''}>${l}</option>`).join('');let f=inputField('Tên công việc / sự kiện','title','text',old?.title||'','maxlength="120" required',true)+inputField('Loại','kind','select',options([['task','Công việc'],['event','Sự kiện'],['health','Sức khỏe']],old?.kind||'task'),'required')+inputField('Ngày','date','date',old?.date||selected,'required')+inputField('Giờ','time','time',old?.time||'')+inputField('Ghi chú','note','text',old?.note||'','maxlength="250"',true);showModal(old?'Sửa kế hoạch':'Thêm công việc / sự kiện',f,fd=>{let title=String(fd.get('title')||'').trim(),date=fd.get('date');if(!title||!date){notify('Vui lòng nhập tên và ngày.');return false}let obj={id:id||newId(),title,kind:fd.get('kind'),date,time:fd.get('time'),note:String(fd.get('note')||'').trim(),done:old?.done||false};appData.tasks=id?appData.tasks.map(x=>x.id===id?obj:x):[...appData.tasks,obj];selected=date;let d=parseDate(date);cursor=new Date(d.getFullYear(),d.getMonth(),1,12);return 'Đã lưu kế hoạch.'},old)}
function wireChecks(root){root.querySelectorAll('[data-check]').forEach(b=>b.onchange=()=>{let t=appData.tasks.find(t=>t.id===b.dataset.check);if(t){t.done=b.checked;saveCloud();renderAll();renderDayDetail()}})}
function deleteTx(id){if(confirm('Bạn có chắc muốn xóa giao dịch này?')){appData.transactions=appData.transactions.filter(t=>t.id!==id);saveCloud();renderAll();notify('Đã xóa giao dịch.')}}
$('addfinance').onclick=()=>openFinance();$('addtask').onclick=$('addtask2').onclick=()=>openTask();$('filtertype').onchange=renderFinance;$('filtermonth').value=monthKey(cursor);$('filtermonth').onchange=renderFinance;$('taskfilter').onchange=renderTasks;$('taskstatus').onchange=renderTasks;$('statsmonth').value=monthKey(today);$('statsmonth').onchange=renderStats;$('settingsform').onsubmit=e=>{e.preventDefault();appData.settings.goal=Math.max(0,Number($('goal').value)||0);appData.settings.budget=Math.max(0,Number($('budget').value)||0);saveCloud();renderAll();notify('Đã lưu mục tiêu.')};
async function startFirebase(){
 if(!configured){$('subtitle').textContent='Cần cấu hình Firebase trước khi sử dụng';$('login').onclick=()=>notify('Mở README.md và dán firebaseConfig từ Firebase Console vào public/app.js.');return}
 const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);try{await getRedirectResult(auth)}catch(e){console.error(e);notify('Đăng nhập chuyển hướng chưa hoàn tất.')}
 onAuthStateChanged(auth,async u=>{if(unsubscribe){unsubscribe();unsubscribe=null}user=u;ready=false;
 $('login').classList.toggle('hidden',!!u);$('logout').classList.toggle('hidden',!u);$('userlabel').textContent=u?(u.displayName||u.email):'Chưa đăng nhập';$('loginhint').classList.toggle('hidden',!!u);
 if(!u){appData={transactions:[],tasks:[],settings:{goal:10000000,budget:8000000}};renderAll();$('subtitle').textContent='Đăng nhập để tải dữ liệu riêng tư';return}
 $('subtitle').textContent='Đang tải dữ liệu an toàn…';const ref=doc(db,'users',u.uid,'app','data');
 unsubscribe=onSnapshot(ref,snap=>{if(snap.exists()){const d=snap.data();appData={transactions:Array.isArray(d.transactions)?d.transactions:[],tasks:Array.isArray(d.tasks)?d.tasks:[],settings:{goal:10000000,budget:8000000,...(d.settings||{})}}}else{appData={transactions:[],tasks:[],settings:{goal:10000000,budget:8000000}};setDoc(ref,{...appData,updatedAt:Date.now(),schemaVersion:1}).catch(console.error)}ready=true;renderAll();$('subtitle').textContent='Đã đồng bộ dữ liệu đám mây'},e=>{console.error(e);notify('Không đọc được dữ liệu. Kiểm tra Firestore Rules.');$('subtitle').textContent='Lỗi đọc dữ liệu'});
 });
 $('login').onclick=async()=>{try{await signInWithPopup(auth,new GoogleAuthProvider())}catch(e){if(['auth/popup-blocked','auth/operation-not-supported-in-this-environment'].includes(e.code)){await signInWithRedirect(auth,new GoogleAuthProvider())}else{console.error(e);notify('Đăng nhập thất bại: '+(e.code||e.message))}}};
 $('logout').onclick=async()=>{if(confirm('Đăng xuất khỏi Life & Money?')){await signOut(auth);notify('Đã đăng xuất.')}}
}
renderAll();startFirebase();
